name: Compilation

on: [push]

jobs:
  run-tests:
    name: Compilation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: Check out

      - name: Install NPM depencies
        run: npm i

      - name: Compile
        run: npm run compile
