name: Tests

on: [push]

jobs:
  run-tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: Check out

      - name: Install NPM depencies
        run: npm i

      - name: Run tests
        run: npm run test
